### PR TITLE
Add name option

### PR DESCRIPTION
**Pull request by overby-me**

### CODE REVIEW

**Comment by freundTech** [comment]
Thanks for the PR.
Do you have a specific use case you would need this for?
The optional argument to the BusManager classes is mainly meant for people wanting to use this as a library in their own program.
I don't really see a use for exposing it on the cli interface and would like to keep that small. If there is a good use case I might still add it though.

**Comment by overby-me** [comment]
I have installed various Spotify plugins to Emacs that connects to the `spotify` dbus app name, and with this change I can use SpotPRIS2 as a drop-in replacement without needing to change any of the plugins.

**Comment by freundTech** [comment]
That would only work if spotpris is running in --auto mode (SingleBusManager), as MultiBugManager always puts a postfix on the bus name in order to differentiate the devices.

Do you think a "steal bus name" option, which makes spotpris use the spotify bus name if it is free would be enough for your use case?
I started work on that already. My idea with it was to steal the bus name to prevent spotify from offering it's own mpris interface, but it would be easy to then make spotpris use that bus name instead of just stealing it.

**Comment by overby-me** [comment]
> That would only work if spotpris is running in --auto mode (SingleBusManager), as MultiBugManager always puts a postfix on the bus name in order to differentiate the devices.

I know. I was also using `-a`.

> Do you think a "steal bus name" option, which makes spotpris use the spotify bus name if it is free would be enough for your use case?
I started work on that already. My idea with it was to steal the bus name to prevent spotify from offering it's own mpris interface, but it would be easy to then make spotpris use that bus name instead of just stealing it.

That would be perfect. Thank you.

**Comment by freundTech** [comment]
I implemented bus name stealing in commit c11006f2c1ba4077f7cad7766acfd24441d0edd2.
For your use case you probably want to pass `-a -s`.
spotPRIS2 needs to be started before Spotify for the name stealing to succeed.

I'll probably release a new version with this feature in a few days.

**Pull request closed without merging**
